$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
words:
  - Treant
  - Leshen
  - Bouldershield
  - Spearshield
  - Bearpelt
  - Bonespine
  - Elderwood
  - Greatsword
  - Brittlebark
  - Storemcloud
  - Lifethread
  - Stoneslab
  - Steelbond
  - Iceblade
  - eseidel
  - Stormcloud
  - mocktail
  - Ironskin
  - Swiftstrike
  - Razortusk
  - sublist
  - Overhealing