name: he_is_coming
description: Simulator for the game "He is Coming"
version: 0.0.1
repository: https://github.com/eseidel/he_is_coming_sim

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  collection: ^1.19.0
  mason_logger: ^0.2.16
  meta: ^1.15.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
