/* This file is generated by bin/generate_items.dart */

import 'package:he_is_coming_sim/item.dart';

class Items {
  static final emergencyShield = Item(
    'Emergency Shield',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final fortifiedGauntlet = Item(
    'Fortified Gauntlet',
    Kind.clothing,
    Rarity.rare,
    Material.leather,
  );
  static final haymaker = Item(
    'Haymaker',
    Kind.weapon,
    Rarity.common,
    Material.leather,
  );
  static final heartDrinker = Item(
    'Heart Drinker',
    Kind.weapon,
    Rarity.common,
    Material.sanguine,
  );
  static final ironGreatsword = Item(
    'Iron Greatsword',
    Kind.weapon,
    Rarity.common,
    Material.stone,
  );
  static final leatherGloves = Item(
    'Leather Gloves',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final leatherVest = Item(
    'Leather Vest',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final phantomArmor = Item(
    'Phantom Armor',
    Kind.clothing,
    Rarity.rare,
    Material.leather,
  );
  static final redwoodCloak = Item(
    'Redwood Cloak',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final redwoodHelmet = Item(
    'Redwood Helmet',
    Kind.clothing,
    Rarity.common,
    Material.wood,
  );
  static final redwoodRod = Item(
    'Redwood Rod',
    Kind.weapon,
    Rarity.common,
    Material.wood,
  );
  static final spearshieldLance = Item(
    'Spearshield Lance',
    Kind.weapon,
    Rarity.common,
    Material.leather,
  );
  static final stoneSteak = Item(
    'Stone Steak',
    Kind.food,
    Rarity.common,
    Material.stone,
  );
  static final weightedBracelet = Item(
    'Weighted Bracelet',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final woodenStick = Item(
    'Wooden Stick',
    Kind.weapon,
    Rarity.common,
    Material.leather,
  );
}
