/* This file is generated by bin/generate_items.dart */

import 'package:he_is_coming_sim/item.dart';

class Items {
  static final EmergencyShield = Item(
    'Emergency Shield',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final FortifiedGauntlet = Item(
    'Fortified Gauntlet',
    Kind.clothing,
    Rarity.rare,
    Material.leather,
  );
  static final Haymaker = Item(
    'Haymaker',
    Kind.weapon,
    Rarity.common,
    Material.leather,
  );
  static final HeartDrinker = Item(
    'Heart Drinker',
    Kind.weapon,
    Rarity.common,
    Material.sanguine,
  );
  static final IronGreatsword = Item(
    'Iron Greatsword',
    Kind.weapon,
    Rarity.common,
    Material.stone,
  );
  static final LeatherGloves = Item(
    'Leather Gloves',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final LeatherVest = Item(
    'Leather Vest',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final PhantomArmor = Item(
    'Phantom Armor',
    Kind.clothing,
    Rarity.rare,
    Material.leather,
  );
  static final RedwoodCloak = Item(
    'Redwood Cloak',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final RedwoodHelmet = Item(
    'Redwood Helmet',
    Kind.clothing,
    Rarity.common,
    Material.wood,
  );
  static final RedwoodRod = Item(
    'Redwood Rod',
    Kind.weapon,
    Rarity.common,
    Material.wood,
  );
  static final SpearshieldLance = Item(
    'Spearshield Lance',
    Kind.weapon,
    Rarity.common,
    Material.leather,
  );
  static final StoneSteak = Item(
    'Stone Steak',
    Kind.food,
    Rarity.common,
    Material.stone,
  );
  static final WeightedBracelet = Item(
    'Weighted Bracelet',
    Kind.clothing,
    Rarity.common,
    Material.leather,
  );
  static final WoodenStick = Item(
    'Wooden Stick',
    Kind.weapon,
    Rarity.common,
    Material.leather,
  );
}
