name: he_is_coming
description: Simulator for the game "He is Coming"
version: 0.0.1
repository: https://github.com/eseidel/he_is_coming_sim
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  json_diff: ^0.2.1
  meta: ^1.15.0
  path: ^1.9.0
  scoped_deps:
    git:
      url: https://github.com/shorebirdtech/shorebird.git
      path: packages/scoped_deps
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^6.0.0
