# cspell:words cupertino
name: ui
description: "UI for the he_is_coming simulator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  he_is_coming:
    path: ../he_is_coming
  material_symbols_icons: ^4.2785.1
  nes_ui: ^0.20.0
  super_tooltip: ^2.0.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/he_is_coming/data/blade_oils.yaml
    - packages/he_is_coming/data/creatures.yaml
    - packages/he_is_coming/data/edges.yaml
    - packages/he_is_coming/data/items.yaml
    - packages/he_is_coming/data/triggers.yaml
    - packages/he_is_coming/data/challenges.yaml
    - packages/he_is_coming/data/sets.yaml
    - assets/steam_logo.png
    - assets/github-mark-white.png